### ISSUE TITLE
paddle_OCR tensorRT 

### ISSUE THREAD

**Issue by itachi176** [tsuting/Jetson_PaddlePaddle_detection#3]
how can I have 'ch_PP-OCRv2_det_infer.onnx_b1_gpu0_fp32.engine'? which tool have you used? thank authors.

**Comment by xiaolul** [comment]
We use nvidia trt_exec to convert. please see doc: https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#using-trtexec-gen-dla-load
You could also check this directory in this repo (specifically this file py-tensorrt-text-detection/trt_utils.py), for how to convert using python sdk

**Comment by itachi176** [comment]
thank you for your information!
